markdown: kramdown
highlighter: rouge
gems:  [jekyll-feed,jekyll-paginate]
paginate: 3
url: https://servicefactoryghent.github.io/
title: "Service Factory"
description:  "Get your latest info about Service Factory here."
author: HansF