markdown: kramdown
highlighter: rouge
plugins:  [jekyll-feed]
url: https://servicefactoryghent.github.io/
title: "Service Factory"
description:  "Get your latest info about Service Factory here."
author: HansF